# In this directory, run the following command to build this builder.
# $ gcloud builds submit . --config=cloudbuild.yaml

# See docs at https://www.terraform.io/docs/index.html
steps:
- name: 'gcr.io/cloud-builders/wget'
  args: ["https://releases.hashicorp.com/terraform/${_TF_VERSION}/terraform_${_TF_VERSION}_linux_amd64.zip"]          
  id: 'fetch-tf'

- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/terraform:${_TF_VERSION}',
        '-t', 'gcr.io/$PROJECT_ID/terraform',
        '--build-arg', 'TF_VERSION=${_TF_VERSION}',
        '--build-arg', 'TF_VERSION_SHA256SUM=${_TF_VERSION_SHA256SUM}',
        '.']
  waitFor: ['fetch-tf']
  id: 'build-docker-image'

- name: gcr.io/cloud-builders/gcloud
  entrypoint: 'bash'
  args: [ '-c', 'mkdir ~/.config ; mkdir ~/.config/gcloud ; gcloud secrets versions access latest --secret=${_SECRET_MANAGER_NAME} > ~/.config/gcloud/application_default_credentials.json' ]
  waitFor: ['fetch-tf', 'build-docker-image']
  id: 'get-serviceaccount'

substitutions:
  _TF_VERSION: 0.13.1
  _TF_VERSION_SHA256SUM: f7b842d1c06045b496fd00db83520e83a974a294b070dbaf88cb1013c5f02caf
  _SECRET_MANAGER_NAME: cloudbuild-sa

images:
- 'gcr.io/$PROJECT_ID/terraform:latest'
- 'gcr.io/$PROJECT_ID/terraform:$_TF_VERSION'
tags: ['cloud-builders-community']
